name: CloudFox GCP

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  cloudfox-gcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Escribir la key JSON en un archivo temporal
      - name: Configurar credenciales GCP
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > $HOME/gcp-key.json
          cat $HOME/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json" >> $GITHUB_ENV

      # 2. Instalar CloudFox
      - name: Instalar Cloudfox
        run: |
          sudo apt update
          wget --retry-connrefused --tries=20 https://github.com/BishopFox/cloudfox/releases/download/v1.15.0/cloudfox-linux-amd64.zip
          unzip cloudfox-linux-amd64.zip

      # 3. Ejecutar CloudFox
      - name: Ejecutar Cloudfox (GCP)
        env:
          GCP_PROJECT_ID: infra-odyssey-331604
        run: |
          mkdir -p cspm
          cd cloudfox
          chmod +x cloudfox
          ./cloudfox gcp whoami --project $GCP_PROJECT_ID --outdir ${{ github.workspace }}/cspm/


