name: CloudFox GCP

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  cloudfox-gcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # --- Instalación de CloudFox ---
      - name: Instalar Cloudfox
        run: |
          sudo apt-get update -y
          wget -q --retry-connrefused --tries=20 https://github.com/BishopFox/cloudfox/releases/download/v1.15.0/cloudfox-linux-amd64.zip
          unzip -q cloudfox-linux-amd64.zip

      # --- Ejecución de CloudFox con SA Key (secreto en GitHub) ---
      - name: Ejecutar Cloudfox (GCP)
        env:
          GCP_PROJECT_ID: infra-odyssey-331604
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/sa.json
        run: |
          # Crear archivo JSON desde el secreto guardado en GitHub
          echo '${{ secrets.GCP_SA_KEY_JSON }}' > "$GOOGLE_APPLICATION_CREDENTIALS"

          # Entrar al directorio y ejecutar el binario
          cd cloudfox
          chmod +x cloudfox
          ./cloudfox gcp whoami --project "$GCP_PROJECT_ID"
          ./cloudfox gcp all-checks --project "$GCP_PROJECT_ID" \
            --outdir "${{ github.workspace }}/cspm/"
        continue-on-error: true

      # --- Publicación de artefactos ---
      - name: Publicar artefactos
        uses: actions/upload-artifact@v4
        with:
          name: cloudfox-gcp
          path: cspm
