name: CloudFox GCP

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  cloudfox-gcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auth GCP (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/534686086869/locations/global/workloadIdentityPools/scitum-infra-odyssey-331604/providers/github
          service_account: ScitumAssessment@infra-odyssey-331604.iam.gserviceaccount.com
          create_credentials_file: true
          export_environment_variables: true

      - name: Instalar Cloudfox
        run: |
          sudo apt update
          wget --retry-connrefused --tries=20 https://github.com/BishopFox/cloudfox/releases/download/v1.15.0/cloudfox-linux-amd64.zip
          unzip cloudfox-linux-amd64.zip

      - name: Ejecutar Cloudfox (GCP)
        run: |
          cd cloudfox
          chmod +x cloudfox
          ./cloudfox gcp whoami --outdir ${{ github.workspace }}/cspm/
        continue-on-error: true

      - name: Publicar artefactos
        uses: actions/upload-artifact@v4
        with:
          name: cloudfox-gcp
          path: cspm
