permissions:
  id-token: write
  contents: read

jobs:
  scoutsuite-gcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auth GCP (OIDC)
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/534686086869/locations/global/workloadIdentityPools/testpool-0003/providers/github-provider
          service_account: quickassessment@infra-odyssey-331604.iam.gserviceaccount.com
          token_format: access_token
          create_credentials_file: true   # <- crea GOOGLE_APPLICATION_CREDENTIALS

      - name: Ejecutar ScoutSuite (GCP)
        env:
          GCP_PROJECT_ID: infra-odyssey-331604
        run: |
          mkdir -p cspm
          pip3 install scoutsuite jq
          # Usa el archivo efímero creado por el paso de auth
          scout gcp -s "$GOOGLE_APPLICATION_CREDENTIALS" --project-id "$GCP_PROJECT_ID" \
            --report-dir './cspm/' --report-name 'sci-cloud' --result-format json
          tail ./cspm/scoutsuite-results/scoutsuite_results_sci-cloud.js -n +2 | jq '.' > ./cspm/scoutsuite_results_sci-cloud.json
        continue-on-error: true
