name: Validar GCP con OIDC y POOL_ID dinámico

on:
  workflow_dispatch:
    inputs:
      pool_id:
        description: "ID del Workload Identity Pool"
        required: true
      project_id:
        description: "ID del proyecto evaluado"
        required: true
      project_number:
        description: "Número de proyecto"
        required: true
      serviceaccount:
        description: "Cuenta de servicio"
        required: true

jobs:
  auth-gcp:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Autenticarse en GCP con OIDC
      uses: google-github-actions/auth@v2
      with:
        token_format: 'id_token'
        id_token_audience: 'sts.googleapis.com'
        workload_identity_provider: projects/${{ github.event.inputs.project_number }}/locations/global/workloadIdentityPools/${{ github.event.inputs.pool_id }}/providers/github-provider
        service_account: ${{ github.event.inputs.serviceaccount }}
        create_credentials_file: true
        export_environment_variables: true
        universe: googleapis.com
        cleanup_credentials: true
        access_token_lifetime: 3600s
        access_token_scopes: https://www.googleapis.com/auth/cloud-platform
        id_token_include_email: false

    - name: Verificar autenticación
      run: |
        echo "Inputs recibidos:"
        echo "Pool ID: ${{ github.event.inputs.pool_id }}"
        echo "Project ID: ${{ github.event.inputs.project_id }}"
        echo "Project Number: ${{ github.event.inputs.project_number }}"
        echo "Service Account: ${{ github.event.inputs.serviceaccount }}"

        gcloud auth list
        gcloud config set project "${{ github.event.inputs.project_id }}"
        gcloud compute project-info describe

    - name: Ejecutar ScoutSuite (GCP)
      run: |
        mkdir -p cspm
        pip3 install scoutsuite jq
        scout gcp --project-id infra-odyssey-331604 --report-dir './cspm/' --report-name 'sci-cloud' --result-format json
        tail ./cspm/scoutsuite-results/scoutsuite_results_sci-cloud.js -n +2 | jq '.' > ./cspm/scoutsuite_results_sci-cloud.json
      continue-on-error: true